Fix compilation error
/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:859
source-map-support.js:722
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
source-map-support.js:722
           ^
source-map-support.js:722
TSError: ⨯ Unable to compile TypeScript:
source-map-support.js:726
packages/data-sources/fetch/stops/stops.ts(65,5): error TS2322: Type '{ from: string; to: string; stops: (Stop | null)[]; }[]' is not assignable to type 'Direction[]'.
source-map-support.js:726
  Type '{ from: string; to: string; stops: (Stop | null)[]; }' is not assignable to type 'Direction'.
source-map-support.js:726
    Types of property 'stops' are incompatible.
source-map-support.js:726
      Type '(Stop | null)[]' is not assignable to type 'Stop[]'.
source-map-support.js:726
        Type 'Stop | null' is not assignable to type 'Stop'.
source-map-support.js:726
          Type 'null' is not assignable to type 'Stop'.
source-map-support.js:726

source-map-support.js:726
    at createTSError (/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:859:12)
source-map-support.js:726
    at reportTSError (/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:863:19)
source-map-support.js:726
    at getOutput (/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:1077:36)
source-map-support.js:726
    at Object.compile (/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:1433:41)
source-map-support.js:726
    at Module.m._compile (/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:1617:30)
source-map-support.js:726
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
source-map-support.js:726
    at Object.require.extensions.<computed> [as .ts] (/Users/henrybrent/Local/GitHub/supertram-tracker/node_modules/ts-node/src/index.ts:1621:12)
source-map-support.js:726
    at Module.load (node:internal/modules/cjs/loader:1288:32)
source-map-support.js:726
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
source-map-support.js:726
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
source-map-support.js:726
  diagnosticCodes: [ 2322 ]
source-map-support.js:726
}
source-map-support.js:726
Process exited with code 1